# Generated by Django 6.0.3 on 2026-03-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bucketitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='bucket_photos/'),
        ),
    ]
